### ISSUE TITLE
v5.14.26.1 Stable

### ISSUE THREAD

**Issue by nnae06** [jkunczik/home-assistant-omada#34] opened 2024-08-14 06:36 UTC
Just wondering when the stable version might be updated.

**Comment by Evanito** [comment] 2024-08-15 02:16
Oh nice, yep it's finally released https://www.tp-link.com/us/support/download/omada-software-controller/

Looking forward :)

**Comment by Evanito** [comment] 2024-10-07 18:51
But "stable" apparently means "waiting for next GA release" per https://github.com/mbentley/docker-omada-controller/issues/418#issuecomment-2378873393

**Comment by imc67** [comment] 2024-10-16 04:19
TP-Link finally released a new version and so did mbently. Can’t wait to see an update on Home Assistant @jkunczik

**Comment by stefanoferrario** [comment] 2024-10-22 22:19
I’m waiting for the new version too on HA

**Comment by jkunczik** [comment] 2024-10-26 22:34
I am currently working on updating the beta plugin. I wil get back to you as soon as I am finished.

**Comment by jkunczik** [comment] 2024-10-27 11:20
I updated Omada Beta to 5.14.32.2. It is not in the Docker Image Registry yet, but will be built locally. Since I am currently using the original Docker Image from Mark Bentley, I am not able to fully test everything. I only tested it on a blank Home Assistant test VM and did not include my network devices into the test. 

Because install.sh and and entrypoint.sh deviated quite significantly from the upstream source, I completely merged them and moved the Home Assistant specific code to the beginning/end of these files. This should allow us to make maintanence easier in the long run. Also, I stopped from persisting the whole `opt/tplink/EAPController` dir. Now only `opt/tplink/EAPController/data` and `opt/tplink/EAPController/logs` are peristed. 

** Please config this does not break anything in your setups and make a backup before updating** 

@DraTrav: If everything works, could you build and push the new images to the Image Repository and enable pulling images in the config.yaml again?

**Comment by DraTrav** [comment] 2024-10-27 13:18
It succeeded in updating, though it did make me reconfigure it. 

it persisted after a restart so I'm really unsure what happened.

Anyways anyone who is updating make sure you save a configuration file before you do so

Docker image is uploaded and the repository is changed.

**Comment by jeakob** [comment] 2024-10-27 14:32
Update shows up but I get the following error when running the update:

> Can't install dratrav/home-assistant-omada-stable:5.14.7: 404 Client Error for http+docker://localhost/v1.47/images/create?tag=5.14.7&fromImage=dratrav%2Fhome-assistant-omada-stable&platform=linux%2Famd64: Not Found ("manifest for dratrav/home-assistant-omada-stable:5.14.7 not found: manifest unknown: manifest unknown")

**Comment by axute** [comment] 2024-10-27 14:57
> Update shows up but I get the following error when running the update:
> 
> > Can't install dratrav/home-assistant-omada-stable:5.14.7: 404 Client Error for http+docker://localhost/v1.47/images/create?tag=5.14.7&fromImage=dratrav%2Fhome-assistant-omada-stable&platform=linux%2Famd64: Not Found ("manifest for dratrav/home-assistant-omada-stable:5.14.7 not found: manifest unknown: manifest unknown")

same here

**Comment by jkunczik** [comment] 2024-10-27 15:24
Thanks @DraTrav ! 

I fear the persistence thing stems from the fact that I changed the symlinks. I had hoped that becuase their relative path in `/data` was the same as before there shouldn't be any issue. Maybe it has something to do with the way I am checking if `/data/data`is empty

https://github.com/jkunczik/home-assistant-omada/blob/b93b6018414b0b3757488eb4ce13376b00bbf103/Omada%20Beta/entrypoint.sh#L11

**Comment by DraTrav** [comment] 2024-10-27 15:31
Ah sorry, I see what I did wrong with stable @axute @jeakob should be fixed now.

**Comment by jkunczik** [comment] 2024-10-27 15:39
I forgot to mention that I also moved v5.14.7 to stable 😞. As a result, @DraTrav has not yet published the corresponding image in the Docker repository. As a workaround, I temporarily changed the image source to omada-beta. You should now be able to update the stable version as well. However, please note that this is just the tested version from beta (v5.14.7) and not yet the updated version 5.14.32.2. Once I receive sufficient feedback that the beta version is working as intended, we can also make it available for stable.

@DraTrav: I saw you last comment, thanks for the quick fix. However, I noticed that the image hast the tag 5.14.30.7. Hence I left the config on beta for now. Can you easily change the image tag? If not, I will change the version of stable to match the Docker Hub version. 

For the future, to make moving builds from beta to stable more easy, I am thinking about using the same subprepo for both versions (just with different versions). We could then also just use one Image repository over on Docker hub (again referencing different versions). What are your thoughts?

**Comment by DraTrav** [comment] 2024-10-27 15:57
@jkunczik I was considering the same thing, I think that's a good plan over what we have currently.

**Comment by stefanoferrario** [comment] 2024-10-27 17:22
> It succeeded in updating, though it did make me reconfigure it.
> 
> it persisted after a restart so I'm really unsure what happened.
> 
> Anyways anyone who is updating make sure you save a configuration file before you do so
> 
> The docker image is uploaded and the repository is changed.

@DraTrav @jkunczik If I understand correctly, does the update require you to import the controller configuration again?

**Comment by DraTrav** [comment] 2024-10-27 17:40
@stefanoferrario Yes it does for just a quick reconfiguration

**Comment by stefanoferrario** [comment] 2024-10-27 17:54
> @stefanoferrario Yes it does for just a quick reconfiguration

@DraTrav thanks for your quick response. Will be the same for historical data and statistics? The last time I migrated the controller I had to rename all the devices as the configuration restore did not carry the data related to the new name assigned to the devices and the statistics were also lost.

**Comment by schorschi1981** [comment] 2024-10-27 19:56
Hey the issue is already there.

Can't install dratrav/home-assistant-omada-stable:5.14.7: 404 Client Error for http+docker://localhost/v1.47/images/create?tag=5.14.7&fromImage=dratrav%2Fhome-assistant-omada-stable&platform=linux%2Famd64: Not Found ("manifest for dratrav/home-assistant-omada-stable:5.14.7 not found: manifest unknown: manifest unknown")

**Comment by DraTrav** [comment] 2024-10-27 21:22
> Hey the issue is already there.
> 
> 
> 
> Can't install dratrav/home-assistant-omada-stable:5.14.7: 404 Client Error for http+docker://localhost/v1.47/images/create?tag=5.14.7&fromImage=dratrav%2Fhome-assistant-omada-stable&platform=linux%2Famd64: Not Found ("manifest for dratrav/home-assistant-omada-stable:5.14.7 not found: manifest unknown: manifest unknown")

Should be fixed. Lmk if it happens again

**Comment by Evanito** [comment] 2024-10-27 22:18
> > Hey the issue is already there.
> > Can't install dratrav/home-assistant-omada-stable:5.14.7: 404 Client Error for http+docker://localhost/v1.47/images/create?tag=5.14.7&fromImage=dratrav%2Fhome-assistant-omada-stable&platform=linux%2Famd64: Not Found ("manifest for dratrav/home-assistant-omada-stable:5.14.7 not found: manifest unknown: manifest unknown")
> 
> Should be fixed. Lmk if it happens again

Attempting to update now is showing the same error. Freshly rebooted HA so not a cache issue.

**Comment by DraTrav** [comment] 2024-10-28 02:54
Okay, docker didn't upload it the first time, docker is now showing the proper version up for stable and is installing correctly for me.  
Sorry about that @Evanito

**Comment by Evanito** [comment] 2024-10-28 05:00
At least it is a different error now 😅
```
Failed to perform the action update/install. Error updating Omada Controller Stable: Can't install dratrav/home-assistant-omada-stable:5.14.7: 404 Client Error for http+docker://localhost/v1.47/images/dratrav/home-assistant-omada-stable:5.14.7/json: Not Found ("No such image: dratrav/home-assistant-omada-stable:5.14.7")
```

**Comment by Evanito** [comment] 2024-10-28 17:54
The cause is pointed out in #44 

Also, pointing out that the stable config still has this: https://github.com/jkunczik/home-assistant-omada/blob/acc429d3bae5e0d714bfc287a3d38c5feed69f13/Omada%20Stable/config.yaml#L3

**Comment by DraTrav** [comment] 2024-10-29 04:12
The original stable didnt have arm support so my build script didn't include the arm tag for docker. My bad fixed and shouldn't happen again! Can't belive I missed that whoops.

**Closed** 2024-11-12 06:05 UTC
