### ISSUE TITLE
Addon keeps crashing on Raspberry Pi 4 Model B 2G

### ISSUE THREAD

**Issue by koenvangils** [jkunczik/home-assistant-omada#19] opened 2024-01-31 14:35 UTC
Seems similar to issue #10 , both the stable and beta addon keeps crashing on Raspberry Pi 4 Model B 2G.

**Comment by jkunczik** [comment] 2024-02-04 21:29
Thanks for the feedback! Which addon are you using (Stable, or Beta)? Could you provide a log and if you think that `healthcheck.sh` is not executable, try to run it manually? 

Here is a quick how-to, in case you need it: 
1. SSH into the Host (Port 22222 for HA OS),
2. find the id/name of the running addon via `docker ps` and
3. then open a shell by executing `docker exec -it {name or id} bash`. 
4. In the container try to run `./healthcheck.sh`

**Comment by koenvangils** [comment] 2024-02-07 14:59
Thanks for your reply!

I experienced the crashes with both the stable and beta version of the addon. Sadly (for solving this issue), I've since migrated my HA OS installation to a different device. I'm therefore not able to test if healthcheck.sh is executable or not...

**Comment by schorschi1981** [comment] 2024-02-07 21:05
![image](https://github.com/jkunczik/home-assistant-omada/assets/62060020/7039f481-2367-494a-9c1e-fbd9214cba96)

**Comment by jkunczik** [comment] 2024-02-27 22:13
Thanks @schorschi1981  for the tests. I will try to reproduce the findings as soon as I find the time.

**Comment by jkunczik** [comment] 2024-03-26 21:30
I found the time to setup a Home Assistant Operating System  test instance on a Raspberry Pi 4 (8G). 

I checked the filesystem in the running container, but everything seems to be fine there:

```shell
root@7e9b5ada-omada-controller:/# ls -la /
total 76
drwxr-xr-x   1 root  root  4096 Mar 26 21:50 .
drwxr-xr-x   1 root  root  4096 Mar 26 21:50 ..
-rwxr-xr-x   1 root  root     0 Mar 26 21:50 .dockerenv
lrwxrwxrwx   1 root  root     7 Feb 16 09:24 bin -> usr/bin
drwxr-xr-x   2 root  root  4096 Apr 15  2020 boot
drwxr-xr-x   5 omada omada 4096 Mar 26 21:50 data
drwxr-xr-x  17 root  root  4000 Apr  4  2023 dev
-rwxr-xr-x   1 root  root  8785 Mar 26 21:45 entrypoint.sh
drwxr-xr-x   1 root  root  4096 Mar 26 21:50 etc
-rwxr-xr-x   1 root  root   163 Mar 26 21:45 healthcheck.sh
drwxr-xr-x   2 root  root  4096 Apr 15  2020 home
lrwxrwxrwx   1 root  root     7 Feb 16 09:24 lib -> usr/lib
drwxr-xr-x   2 root  root  4096 Feb 16 09:24 media
drwxr-xr-x   2 root  root  4096 Feb 16 09:24 mnt
drwxr-xr-x   1 root  root  4096 Mar 26 21:47 opt
dr-xr-xr-x 306 root  root     0 Mar 26 21:50 proc
drwx------   2 root  root  4096 Feb 16 09:27 root
drwxr-xr-x   5 root  root  4096 Feb 16 09:27 run
lrwxrwxrwx   1 root  root     8 Feb 16 09:24 sbin -> usr/sbin
drwxr-xr-x   2 root  root  4096 Feb 16 09:24 srv
dr-xr-xr-x  12 root  root     0 Mar 26 21:50 sys
drwxrwxrwt   1 root  root  4096 Mar 26 21:54 tmp
drwxr-xr-x   1 root  root  4096 Feb 16 09:24 usr
drwxr-xr-x   1 root  root  4096 Feb 16 09:27 var
```
`/healthcheck.sh` (not `./healthcheck.sh`, sorry my bad) is executable and the container is running over 30 minutes on my system (according to `docker ps`): 

```
8f8f82e24c19   7e9b5ada/aarch64-addon-omada_controller:5.13.3                  "/entrypoint.sh /usr…"   31 minutes ago   Up 31 minutes (healthy)   0.0.0.0:8043->8043/tcp, :::8043->8043/tcp, 0.0.0.0:8088->8088/tcp, :::8088->8088/tcp, 0.0.0.0:8843->8843/tcp, :::8843->8843/tcp, 0.0.0.0:29810-29813->29810-29813/udp, :::29810-29813->29810-29813/udp, 0.0.0.0:29810-29816->29810-29816/tcp, :::29810-29816->29810-29816/tcp, 0.0.0.0:29815-29816->29815-29816/udp, :::29815-29816->29815-29816/udp   addon_7e9b5ada_omada_controller
```

There has to be something else killing the container. Maybe the system is out of RAM? After all Omada is quite resource-hungry. On my system it is using 1.96 GB of RAM. 

```
CONTAINER ID   NAME                              CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
8f8f82e24c19   addon_7e9b5ada_omada_controller   2.95%     1.196GiB / 3.702GiB   32.29%    602kB / 11.8MB    528kB / 32MB      169
```

**Comment by DraTrav** [comment] 2024-05-06 22:25
I imagine this issue is caused by the system failing to build the actual container once I finish #5 it should become less of an issue.

**Comment by DraTrav** [comment] 2024-05-09 03:02
#5 An image is now being hosted and should allow it just to be created, Ill acquire a rasp pi 2g when I am able and test this.

**Comment by jkunczik** [comment] 2024-06-06 17:57
Thanks @DraTrav! I will close this issue for now. If the problem still persists, please leave a comment.

**Closed by jkunczik** 2024-06-06 17:57 UTC
